### ISSUE TITLE
Cloned repositories do not persist between deployments

### ISSUE THREAD

**Issue by strogonoff** [ietf-ribose/bibxml-service#98] opened 2022-01-25 16:21 UTC
This means after each deploy indexing takes longer (repository must be cloned again instead of just pulling what changed). The task now logs a warning when this happens.

**Comment by ronaldtse** [comment] 2022-01-26 11:16
This is normal though. We don't really want persistence because it means resources are persistent.

**Comment by strogonoff** [comment] 2022-01-26 14:11
Not sure what's inherently bad about persistence

**Comment by ronaldtse** [comment] 2022-02-18 16:43
Because every job is run independently by an independent container. Feature not a bug. Closing.

**Closed by ronaldtse** 2022-02-18 16:43 UTC
Labels: ⚙️ ops
