### ISSUE TITLE
Mapping is not resolved correctly for underscore-prefixed files

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/bibxml-service#232] opened 2022-07-15 00:55 UTC
## Problematic: Reference files that start with `_reference.W3C.{name}`

These files seem to directly fall back to the backup files without any XML processing. We want the `_reference.W3C.{name}` paths to resolve to `reference.W3C.{name}`.

<img width="836" alt="Screenshot 2022-07-15 at 9 38 52 AM" src="https://user-images.githubusercontent.com/11865/179123809-41296d49-d549-48b3-9cf5-4026ab1c4659.png">

The other `_reference.{publisher name}.{name}` patterns to be processed by the BibXML Service.

<img width="838" alt="Screenshot 2022-07-15 at 9 39 47 AM" src="https://user-images.githubusercontent.com/11865/179123908-9b3cc09f-1488-442e-a2a8-dfe58d643142.png">

From https://github.com/ietf-ribose/bibxml-service/issues/222

**Comment by strogonoff** [comment] 2022-07-22 04:09
This should not be so. And I cannot reproduce this behavior on dev.bibxml.org:

- https://dev.bibxml.org/public/rfc/bibxml4/_reference.W3C.xml-c14n.xml
- https://dev.bibxml.org/public/rfc/bibxml4/reference.W3C.xml-c14n.xml

BibXML service strips the optional underscore at the very early stage of processing: see [this expression](https://github.com/ietf-ribose/bibxml-service/blob/18c43996f70550541879c6f2d54d5daac1fa3db5/xml2rfc_compat/models.py#L7-L12).

- Any auto resolution or mapping resolution will happen after the underscore is already ignored.
- The _only_ case where the underscore can matter is if we have no match and fallback must take place: fallback attempts to be as simple as possible, and  both `_reference` and `reference` will fall back to their respective files in bibxml-data-archive. This also means removing either one from the archive will break the fallback.

**Comment by ronaldtse** [comment] 2022-07-22 06:57
@strogonoff thanks. Does this mean that we can remove all `_reference.*` files from the fallback now without affecting functionality (ietf-tools/bibxml-data-archive#14)?

**Comment by ronaldtse** [comment] 2022-07-22 07:28
> I feel like any time a legacy consumer comes up that used those, and it’ll suddenly be a bug that’s more difficult to solve because we don’t have the files anymore.

We do have the files in the other repository (https://github.com/ietf-ribose/bibxml-data-backup). In any case, I do not think we need those files and it is a nightmare to maintain those irrelevant tiles.

**Comment by strogonoff** [comment] 2022-07-22 07:39
But they are relevant, they are instrumental in enabling the simplest possible dumb static server like behavior which ensures foolproof last-resort code path behavior…

> t is a nightmare to maintain those irrelevant files.

My point is that we _shouldn’t maintain_ anything here, and just leave it as is

**Comment by ronaldtse** [comment] 2022-07-22 09:46
> My point is that we shouldn’t maintain anything here, and just leave it as is

It is an ideal but it is not possible:
1. Authoritative datasets change. For example, we may have additional bibitems that we can map to when datasets add them.
2. There may be mistakes in mapping to be fixed.

The "backup" repo is not changed. Only the "fallback" repo is being cleaned.

We just want to remove the "_reference.W3C.*" files. Can you help facilitate that?

**Comment by strogonoff** [comment] 2022-07-22 11:52
Ah! So the issue is that mapping is not having effect for underscore-prefixed items. That’s a bug in mapping resolution.

**Comment by strogonoff** [comment] 2022-07-22 11:56
There are two complaints:

- Mapping is not resolved correctly for underscore-prefixed files (bug).
- There are extra files in the archive for fallback purpose. This creates confusion and possibility of defining duplicate mappings. We may want to strip underscores from all xml2rfc paths at fallback stage. (Not necessarily a bug, but might make maintaining mappings slightly easier.)

**Comment by strogonoff** [comment] 2022-07-28 05:19
This should be fixed now:

- The underscore in `_reference` is now omitted when resolving mappings or obtaining fallback.

  In other words: when it comes to mapping and fallback, the underscore-prefixed equivalent of a path is handled exactly the same as if the path was requested without the underscore. (Logs and metrics still record the path as requested, i.e. the underscore will be preserved there.)

- For example, https://dev.bibxml.org/public/rfc/bibxml6/_reference.IEEE.802.15.4J_2013.xml used to not resolve (it doesn’t exist at http://xml2rfc.tools.ietf.org/public/rfc/bibxml6/_reference.IEEE.802.15.4J_2013.xml, and we have a mapping for it but the mapping doesn’t seem to use the right format). Now it will result in the same outcome as https://dev.bibxml.org/public/rfc/bibxml6/reference.IEEE.802.15.4J_2013.xml.

**Comment by strogonoff** [comment] 2022-07-28 05:20
@ronaldtse I believe this means it’s OK to omit the underscore-prefixed files from the archive, if otherwise warranted. As it is now, they are not used for fallback or mapping resolution anymore.

**Closed by strogonoff** 2022-07-28 05:20 UTC
Labels: bug, retrieval, xml2rfc
