### ISSUE TITLE
Data mismatch when retrieving IEEE standards by xml2rfc paths

### ISSUE THREAD

**Issue by kesara** [ietf-ribose/bibxml-service#31] opened 2021-12-02 21:34 UTC
Current bibxml reference: https://xml2rfc.tools.ietf.org/public/rfc/bibxml6/reference.IEEE.802.11_2012.xml
New bibxml legacy reference: http://34.229.41.119:8000/public/rfc/bibxml6/reference.IEEE_802-11.2012.xml

Note that,
The file name is different:
`reference.IEEE.802.11_2012` vs `reference.IEEE_802-11.2012`.

The `reference` `anchor` attribute data is different:
`anchor="IEEE.802.11_2012"` vs `anchor="IEEE.IEEE 802-11.2012"`

The `organization` data is different:
`<organization>IEEE</organization>` vs `<organization abbrev="IEEE">Institute of Electrical and Electronics Engineers</organization>`

These should match the existing bibxml service references.

**Comment by ronaldtse** [comment] 2021-12-03 02:06
Thank you for the review!

> Current bibxml reference: https://xml2rfc.tools.ietf.org/public/rfc/bibxml6/reference.IEEE.802.11_2012.xml
> New bibxml legacy reference: http://34.229.41.119:8000/public/rfc/bibxml6/reference.IEEE_802-11.2012.xml
> 
> Note that, The file name is different: `reference.IEEE.802.11_2012` vs `reference.IEEE_802-11.2012`.

This is an issue with legacy path handling for IEEE. The anchor might not wish to see changes because the anchors are used in existing documents. We will fix this in #18 (this could be slightly tricky, though).

> The `reference` `anchor` attribute data is different: `anchor="IEEE.802.11_2012"` vs `anchor="IEEE.IEEE 802-11.2012"`

The duplicated "IEEE" is an error. Will be fixed here: relaton/relaton-ieee#11

> The `organization` data is different: `<organization>IEEE</organization>` vs `<organization abbrev="IEEE">Institute of Electrical and Electronics Engineers</organization>`

As discussed with @rjsparks in https://github.com/ietf-ribose/bibxml-service/issues/18#issuecomment-982077903 , the new service does not necessarily guarantee identical content being served at the legacy path.

In this particular case, RFC 7991, 2.35 (`<organization>`) and 2.35.1 (`"abbrev" attribute`) state:

```
2.35.  <organization>

   Specifies the affiliation [RFC7322] of an author.

   This information appears both in the "Author's Address" section and
   on the front page (see [RFC7322] for more information).  If the value
   is long, an abbreviated variant can be specified in the "abbrev"
   attribute.

   This element appears as a child element of <author> (Section 2.7).

   Content model: only text content.

2.35.1.  "abbrev" Attribute

   Abbreviated variant.
```

Technically I would think that the following demonstrates correct usage of the RFC 7991 intent:
```xml
<organization abbrev="IEEE">Institute of Electrical and Electronics Engineers</organization>
```

Of course, if IETF wishes to only use the "IEEE" abbreviation instead of its full name "Institute of Electrical and Electronics Engineers", and thus omit the usage of the `abbrev` attribute, it is totally doable.

@rjsparks can we confirm this particular usage? Thanks.

**Comment by ronaldtse** [comment] 2021-12-03 02:40
I would like to further explain about the data differences between `bibxml6` and the new IEEE bibliographic content from the IEEE database provided by @rjsparks .

In the two paths provided above, there are also other differences (old => new):

* Link: `<reference target=...>` `http://ieeexplore.ieee.org/servlet/opac?punumber=6178209` => `https://ieeexplore.ieee.org/document/6178212`
* DOI value: `10.1109/ieeestd.2012.6178212` => `10.1109/IEEESTD.2012.6178212`
* Publication date: `<date day="5" month="April" year="2012"/>` => `<date year="2012" month="June" day="26"/>`
* Keywords: the legacy content has no keywords but the new one contains multiple.

In addition, the new dataset contains ~9,900 items while the legacy dataset only contains 253.

**Comment by russhousley** [comment] 2021-12-03 14:59
I suspect that we could inform the IEEE about the inconsistency, and they would fix it.

**Comment by ronaldtse** [comment] 2021-12-03 15:02
@russhousley thanks for the suggestion.

In this particular case, the official IEEE data set is correct. The error was only from the legacy data set that will be replaced. 

That said, there are many more errors in the official IEEE data set that we should report. We'll maintain that list as we go on (at least in the dozens if not hundreds).

**Comment by rjsparks** [comment] 2021-12-03 18:10
From the RFC Production Center:

> RPC prefers simply "IEEE" for the organization. (Rationale: commonly known by "IEEE".)
> 
> e.g. preference for output such as
> 
>     [IEEE802.1Q-2011]
>               IEEE, "Local and Metropolitan Area Networks -- Media
>               Access Control (MAC) Bridges and Virtual Bridged Local
>               Area Networks", IEEE Std 802.1Q-2011, August 2011.
> 
> 
> Similarly, preference for "W3C" over "World Wide Web Consortium" in references to W3C documents.
> 
> Example of output from the existing citation library:
> 
>       [W3C.REC-xml11-20060816]
>               Paoli, J., Sperberg-McQueen, C., Yergeau, F., Cowan, J.,
>               Maler, E., and T. Bray, "Extensible Markup Language (XML)
>               1.1 (Second Edition)", World Wide Web Consortium
>               Recommendation REC-xml11-20060816, August 2006,
>               <http://www.w3.org/TR/2006/REC-xml11-20060816>.
> 
> Better as:
>
>       [W3C.REC-xml11-20060816]
>               Paoli, J., Sperberg-McQueen, C., Yergeau, F., Cowan, J.,
>               Maler, E., and T. Bray, "Extensible Markup Language (XML)
>               1.1 (Second Edition)", W3C Recommendation REC-xml11-20060816, 
>               August 2006, <http://www.w3.org/TR/2006/REC-xml11-20060816>.

**Comment by ronaldtse** [comment] 2021-12-03 20:00
Thanks @rjsparks for the clarification. In this case, should we still fill in the `abbrev` value? Or just leave it unset?

**Comment by rjsparks** [comment] 2021-12-03 20:02
Yes, please go ahead and set it.

**Comment by ronaldtse** [comment] 2021-12-05 04:58
Thanks @rjsparks , the abbreviation issue is filed here: https://github.com/relaton/relaton-ietf/issues/48

**Comment by strogonoff** [comment] 2022-02-04 13:09
As an update on this issue.

Current outputs are as follows, in red is https://xml2rfc.tools.ietf.org/public/rfc/bibxml6/reference.IEEE.802.11_2012.xml, in green is https://dev.bibxml.org/public/rfc/bibxml6/reference.IEEE.802.11_2012.xml, without whitespace and punctuation differences:

```diff
-<reference anchor="IEEE.802.11_2012" target="http://ieeexplore.ieee.org/servlet/opac?punumber=6178209">
+<reference target="https://ieeexplore.ieee.org/document/6171799" anchor="IEEE_802-11.2012">
  <front>
-  <title>IEEE Standard for Information technology--Telecommunications and information exchange between systems Local and metropolitan area networks--Specific requirements Part 11: Wireless LAN Medium Access Control (MAC) and Physical Layer (PHY) Specifications</title>
-  <author>
-   <organization>IEEE</organization>
-  </author>
-  <date day="5" month="April" year="2012" />
-  <abstract><t>This revision specifies technical corrections and clarifications to IEEE Std 802.11 for wireless local area networks (WLANS) as well as enhancements to the existing medium access control (MAC) and physical layer (PHY) functions. It also incorporates Amendments 1 to 10 published in 2008 to 2011.</t>
+  <title>IEEE Draft Standard for Local and Metropolitan Area Networks - Specific Requirements - Part 11: Wireless LAN Medium Access Control (MAC) and Physical Layer (PHY) Specifications - Amendment 3: Enhancements for Very High Throughput in the 60 GHz Band</title>
+  <abstract><t>This amendment defines modifications to both the 802.11 physical layers (PHY) and the 802.11 Medium Access Control Layer (MAC) to enable operation in the 60 GHz frequency band capable of very high throughput.</t>
    </abstract>
  </front>
- <seriesInfo name="IEEE" value="802.11-2012" />
- <seriesInfo name="DOI" value="10.1109/ieeestd.2012.6178212" />
+ <seriesInfo name="IEEE" value="p802.11ad/d.6-0"/>
 </reference>
```

Basically, IETF BibXML service returns a different standard. It tries to retrieve most relevant document from our sources, given “802-11.2012” from filename. It uses a rough query probably similar to [this, matching a few of similar standards](https://dev.bibxml.org/search/?bypass_cache=1&query=%24.docid%5B*%5D.id+like_regex+%22IEEE.*802-11%22+%26%26+%24.date%5B*%5D.value+like_regex+%222012-.*%22&query_format=json_path), and guesses one of them. It is unclear to me which of the above standards is the one used on xml2rfc server.

To me it seems there are two separate issues:

- Our our best-effort approach tries to return an up-to-date equivalent from our sources it returns a different standard than what xml2rfc path expected.

  This has issues with complex standard identifiers and/or XML filenames. I don’t know how to address it except by abandoning fuzzy matching within `bibxml6` directory and relying on manual mapping.

- We might not have the requisite standard at all:

  - None of the standards we have use the same “punumber” as the one in xml2rfc response. [Relevant query](https://dev.bibxml.org/search/?bypass_cache=1&query=%24.link%5B*%5D.content+like_regex+%226178209%22&query_format=json_path) returns nothing.
  - [Query by publication date, 5 April 2012](https://dev.bibxml.org/search/?bypass_cache=1&query=%24.docid%5B*%5D.type+%3D%3D+%22IEEE%22+%26%26+%24.date%5B*%5D.value+like_regex+%222012-%5B0%5D%3F4-%5B0%5D%3F5%22&query_format=json_path) does not return any 802-11 standard.
  - I filed this in https://github.com/ietf-ribose/relaton-data-ieee/issues/8

**Comment by rjsparks** [comment] 2022-02-04 14:02
@strogonoff - as Ron noted earlier in the thread, the right one to return the one with this in the footer in the results of your query results:
`[IEEE 802-11.2012](https://dev.bibxml.org/get-one/by-docid/?doctype=IEEE&docid=IEEE%20802-11.2012&query=%24.docid%5B%2A%5D.id%20like_regex%20%22IEEE.%2A802-11%22%20%26%26%20%24.date%5B%2A%5D.value%20like_regex%20%222012-.%2A%22&query_format=json_path&page=1) 978-0-7381-7211-8 10.1109/IEEESTD.2012.6178212`

Note that if you follow `target="http://ieeexplore.ieee.org/servlet/opac?punumber=6178209"` through the first http to https redirect, you get:
`% curl -I "https://ieeexplore.ieee.org/servlet/opac?punumber=6178209"
HTTP/1.1 302 Moved Temporarily
Location: https://ieeexplore.ieee.org/document/6178212`

The name of that document seems the closest in the set returned by your example query?

**Comment by strogonoff** [comment] 2022-02-04 14:14
@rjsparks

Indeed, my bad… Yes, https://ieeexplore.ieee.org/document/6178212 is the one featured in https://dev.bibxml.org/get-one/by-docid/?doctype=IEEE&docid=IEEE%20802-11.2012. I’ll look into adjusting fetching logic to match it more precisely.

Once BibXML service returns the correct document, the following issues will still remain to be dealt with:

- Date mismatch. The document on xml2rfc specifies 2012-04-05 as publication date, but we don’t have that one. I’ll file that in 
- Author mismatch. I guess this answers my question in #100, according to xml2rfc output publishers should be serialized as authors.

**Comment by russhousley** [comment] 2022-02-04 16:59
This (https://ieeexplore.ieee.org/document/6171799) seems to be pointing to the Draft 6.0 of the document during balloting, not the final standard.  I hope that the standard (https://ieeexplore.ieee.org/document/6178212) is actually referenced.  Note that "IEEE Std 802.11-2012" is what actually shows on the cover of the document.

**Comment by strogonoff** [comment] 2022-02-11 12:29
The latest update provides a management utility for checking xml2rfc path resolution:

<img width="1166" alt="Screenshot 2022-02-11 at 1 27 48 PM" src="https://user-images.githubusercontent.com/292959/153591418-1472c56c-84ae-4883-b564-9b3571988f1d.png">

It does not show an error because the automated resolver function doesn’t know the document is wrong. However, it allows to inspect the XML response and manually map the path to desired document ID (which in this case would be IEEE 802-11.2012).

**Comment by ronaldtse** [comment] 2022-02-18 17:35
Having done some extensive comparison of IEEE references, `bibxml6` will require a manual mapping. Many of the previous references are incomplete or conflate draft documents with published documents, and vice versa. Whoever is doing the mapping will be required to compare titles and publication dates.

**Comment by rjsparks** [comment] 2022-02-18 19:15
For the source for bibxml6/bib-ieee are you using just the dump from xml2rfc.tools.ietf.org? As the RFP noted, we had started building a newer resource based on a feed IEEE had provided us, and that should likely have been the basis for comparison. @russhousley @TonyLHansen  - would you spot check what you see at dev.bibxml.org to see if we should take the results of the alternate official feed from IEEE in lieu of previous work? Would it be ok for some older references to fail here, and have to be manually fixed up?

**Comment by strogonoff** [comment] 2022-02-19 21:21
> I put "802.11i" into the search box, and I got two hits. Not sure how that is possible. One includes an ISBN and DOI, but the other does not.

FWIW, one comes from bibxml2 (bibxml-misc) dataset, and the other from a Relaton repository (which is compiled from authoritative source and should be more complete and up-to-date).

The new service supports multiple bibliographic data sources, and sometimes it happens that more than one source provides a bibliographic item for the same document.

By design, items known to represent the same document are meant to be collapsed into a single item in search results (and once you open the page, you’ll still see both citation variants). In this particular case our data sources seem to not facilitate this behavior, which is probably an error.

cc @ronaldtse. If our Relaton sources provided *identical* primary identifier in both instances, they would show as a single document in the search results. However, we have case and possibly punctuation differences, so they display as multiple items in search.

**Comment by ronaldtse** [comment] 2022-02-20 07:20
I have just completed a mapping of the old bibxml6 dataset to the official IEEE dataset ("new" dataset), and also an investigation into the data of the bibxml2 dataset. 

1. The IEEE entries in the bibxml2 dataset are a strict subset of those in bibxml6, so we should remove all IEEE references from bibxml2 to prevent duplication. 
2. In the bibxml6 dataset, some documents cannot be mapped to the official IEEE dataset. This is for two reasons. 
  * the official IEEE dataset, while containing nearly 10,000 entries, is incomplete and misses some data compared to the official IEEE website/webstore. There are a few documents of this type here.
  * the official IETF dataset comes with publicly published drafts. This means that a single document can appear in its different stages within the same query. As @strogonoff mentioned, the service attempts to link them into a single item whenever possible. However, there are two data quality issues: (1) the IEEE dataset is manually curated by IEEE and does not enforce these document relationships, a number of those drafts don't link properly. (2) the IEEE does not use a documented/defined convention for identifying drafts and draft stages, so there are many outliers. 

Can we omit IEEE drafts? Probably not desired for legacy paths: in the mappings we have done, somehow, quite a few items in bibxml2 and bibxml6 point to drafts -- not published IEEE standards.

**Comment by rjsparks** [comment] 2022-02-20 17:07
@russhousley has already mentioned that it's probably fine not to point to IEEE drafts, it I understood him correctly.

**Comment by russhousley** [comment] 2022-02-20 18:54
Yes, that is my view.

**Comment by ronaldtse** [comment] 2022-02-21 02:35
@russhousley @rjsparks yes I understand.

There are a few options for existing bibxml2 and bibxml6 entries:
1. The bibxml2 and bibxml6 entries that point to drafts should no longer resolve.
2. The bibxml2 and bibxml6 entries that point to drafts will point to the published versions.
3. Serve old bibxml2 and bibxml6 entries for the drafts, but this is inconsistent with desired practice, i.e. we serve broken entries.

Which is the desired behavior?

**Comment by TonyLHansen** [comment] 2022-02-21 04:19
A few notes:

- everything in bibxml-misc (nee bibxml2) was created by hand based on need. If something needed to be referenced that didn't fall into one of the other bibxml repos, it would get added to bibxml-misc. 
- the intent of bibxml-ieee, bibxml-nist, bibxml-w3c, bibxml-3gpp, were all supposed to provide something that could be totally data driven AND based on official sources.

If bibxml-misc points to drafts for IEEE documents, that means that in the past someone needed to make such a reference in their document.

The real question is: Should that past need drive future abilities of bibxml-ieee?

A separate question: If IEEE were to remove a standard from their list, should we similarly remove our bibxml pointer for it? Or would it be better to keep a bibxml reference, but mark it somehow as withdrawn?

**Comment by russhousley** [comment] 2022-02-21 13:06
@TonyLHansen.  Good points.

Maybe the drafts in bibxml-misc should stay so the old documents will still work properly, and no new drafts will be added.

I think that an entry in bibxml-ieee, once populated, should remain.  That is, if IEEE deletes it from their files, we keep it as it was last seen.

**Comment by ronaldtse** [comment] 2022-02-21 19:09
> That is, if IEEE deletes it from their files, we keep it as it was last seen.

The IEEE does specially mark a "deleted entry" so nothing is really deleted from the source dataset.

Instead of keeping the drafts in bibxml-misc, it might be wise to just map them to the authoritative "draft" entries in the authoritative dataset. 

While the IEEE dataset does differentiate against "draft", "withdrawn", "approved", "reserved" statuses. However, IEEE standards are fast moving and they often go into "withdrawn" status, and as a result a document that cites it can go out of date fast, so we should not filter out the "withdrawn" ones. So I'm also averse from filtering away "draft" as it makes life a bit more unpredictable.

**Comment by ronaldtse** [comment] 2022-02-21 19:13
But I do understand that there are potential benefits of keeping only "approved" IEEE standards. However, this will also affect the other data sources. For example, citations to W3C standards are often to drafts. The NIST database will also be providing drafts.

**Comment by russhousley** [comment] 2022-02-21 19:33
Yes, IEEE has a 5-year review policy, and they often roll specifications into a "maintenance release" that obsoletes the full-approved standards that get merged.

**Comment by strogonoff** [comment] 2022-04-16 13:50
As an update, problems in original issue description were addressed:

- xml2rfc anchor formatting rules were updated to match legacy behavior more strictly (now we use `docid` with `scope=anchor` in Relaton data for formatting anchors, if available; falling back on first available `docid` if not, which if causes issues later can be reopened)
- filenames are formatted as xml2rfc anchor
- it was agreed that fine details in data can differ if Relaton source in question contains more complete data (e.g., organization abbreviation)

Additionally, some issues with data mismatch are supposed to be resolved by manually mapping Relaton `docid`s to xml2rfc paths and/or updating auto-mapping logic in `xml2rfc_compat.fetchers` (see also https://dev.bibxml.org/static/docs/howto/adjust-xml2rfc-paths.html).

**Comment by strogonoff** [comment] 2022-06-25 11:15
Data mismatch should be eliminated.

- Many of XML files are now mapped to authoritative identifiers.
- However, for most such identifiers bibliographic items are missing in bibliographic sources (e.g., `relaton-data-ieee`), meaning the service falls back to xml2rfc archive XML data verbatim.
- As bibliographic items with mapped identifiers appear in sources, the service will return those bibliographic items serialized to bibxml instead.

See https://github.com/ietf-ribose/bibxml-service/issues/18#issuecomment-1166246395 for an HTML report on all `bibxml6` paths with diffs.

**Closed by strogonoff** 2022-06-25 11:15 UTC
Labels: bug
