### ISSUE TITLE
Running tests

### ISSUE THREAD

**Issue by kesara** [ietf-ribose/bibxml-service#223] opened 2022-06-27 21:42 UTC
Is bibxml-service configured to send coverage reports to codecov?
If so can you point to the coverage reports?

I was trying to run the tests manually using `test.Docker`.
I am getting the following errors:
```
bibxml-service-test-1        | --------------------------------------------------------
bibxml-service-test-1        |  docker-compose-wait 2.7.2
bibxml-service-test-1        | ---------------------------
bibxml-service-test-1        | Starting with configuration:
bibxml-service-test-1        |  - Hosts to be waiting for: [test-db:5432]
bibxml-service-test-1        |  - Timeout before failure: 300 seconds
bibxml-service-test-1        |  - TCP connection timeout before retry: 30 seconds
bibxml-service-test-1        |  - Sleeping time before checking for hosts availability: 30 seconds
bibxml-service-test-1        |  - Sleeping time once all hosts are available: 0 seconds
bibxml-service-test-1        |  - Sleeping time between retries: 30 seconds
bibxml-service-test-1        | --------------------------------------------------------
bibxml-service-test-1        | Waiting 30 seconds before checking for hosts availability
bibxml-service-test-1        | --------------------------------------------------------
bibxml-service-test-1        | Checking availability of test-db:5432
bibxml-service-test-1        | Host test-db:5432 is now available!
bibxml-service-test-1        | --------------------------------------------------------
bibxml-service-test-1        | docker-compose-wait - Everything's fine, the application can now start!
bibxml-service-test-1        | --------------------------------------------------------
bibxml-service-test-db-1     | 2022-06-27 21:41:24.205 UTC [38] ERROR:  duplicate key value violates unique constraint "api_ref_data_ref_dataset_3182f6b6_uniq"
bibxml-service-test-db-1     | 2022-06-27 21:41:24.205 UTC [38] DETAIL:  Key (ref, dataset)=(ref_01, test_dataset_01) already exists.
bibxml-service-test-db-1     | 2022-06-27 21:41:24.205 UTC [38] STATEMENT:  INSERT INTO "api_ref_data" ("dataset", "ref", "body", "latest_date", "representations", "ref_id", "ref_type") VALUES ('test_dataset_01', 'ref_01', '{}', '2022-06-27'::date, '{}', '', '') RETURNING "api_ref_data"."id"
bibxml-service-test-db-1     | 2022-06-27 21:41:28.820 UTC [44] ERROR:  syntax error, unexpected IDENT_P at end of jsonpath input at character 201
bibxml-service-test-db-1     | 2022-06-27 21:41:28.820 UTC [44] STATEMENT:  SELECT "api_ref_data"."id", "api_ref_data"."dataset", "api_ref_data"."ref", "api_ref_data"."body" FROM "api_ref_data" WHERE "api_ref_data"."id" IN (
bibxml-service-test-db-1     | 	        SELECT id FROM api_ref_data WHERE (body @@ 'test')
bibxml-service-test-db-1     | 	    ) ORDER BY "api_ref_data"."latest_date" DESC LIMIT 400
bibxml-service-test-db-1     | 2022-06-27 21:41:29.155 UTC [49] ERROR:  syntax error, unexpected '{', expecting STRING_P at or near "{" of jsonpath input at character 201
bibxml-service-test-db-1     | 2022-06-27 21:41:29.155 UTC [49] STATEMENT:  SELECT "api_ref_data"."id", "api_ref_data"."dataset", "api_ref_data"."ref", "api_ref_data"."body" FROM "api_ref_data" WHERE "api_ref_data"."id" IN (
bibxml-service-test-db-1     | 	        SELECT id FROM api_ref_data WHERE (body @? '$.docid[*] ? (@.id like_regex "(?i)^NONEXISTENTID$" && @.type like_regex {id_type})')
bibxml-service-test-db-1     | 	    ) ORDER BY "api_ref_data"."latest_date" DESC LIMIT 15
bibxml-service-test-1 exited with code 1
Aborting on container exit...
[+] Running 3/3
 ⠿ Container bibxml-service-test-1        Stopped                                                                                                                                                      0.0s
 ⠿ Container bibxml-service-test-redis-1  Stopped                                                                                                                                                      0.2s
 ⠿ Container bibxml-service-test-db-1     Stopped                                                                                                                                                      0.1s
ERRO[0088] 1
```

**Comment by stefanomunarini** [comment] 2022-06-29 09:16
Hi @kesara I'm looking into the issue(s) with running the tests. I'll get back to you when everything's fixed.

As for the Codecov report, the CI is set up to upload the report to Codecov, however a valid token (`CODECOV_TOKEN`) needs to be provided in the repository settings as environment variable

**Comment by strogonoff** [comment] 2022-07-03 09:19
FWIW some failing tests are caused by the fix for #225, due to rushed update test are out of date, should be fixed early next week.

**Comment by kesara** [comment] 2022-07-04 02:07
> Hi @kesara you can run tests locally following the instruction [here](https://dev.bibxml.org/static/docs/howto/run-tests.html).
> 
> I'm still investigating why the tests fail on the GitHub CI, while they pass on the local environment.

BTW tests are still failing for me locally.

```
...
bibxml-service-test-1        | Checking availability of test-db:5432
bibxml-service-test-1        | Host test-db:5432 is now available!
bibxml-service-test-1        | --------------------------------------------------------
bibxml-service-test-1        | docker-compose-wait - Everything's fine, the application can now start!
bibxml-service-test-1        | --------------------------------------------------------
bibxml-service-test-db-1     | 2022-07-04 02:05:05.974 UTC [77] ERROR:  duplicate key value violates unique constraint "api_ref_data_ref_dataset_3182f6b6_uniq"
bibxml-service-test-db-1     | 2022-07-04 02:05:05.974 UTC [77] DETAIL:  Key (ref, dataset)=(ref_01, test_dataset_01) already exists.
bibxml-service-test-db-1     | 2022-07-04 02:05:05.974 UTC [77] STATEMENT:  INSERT INTO "api_ref_data" ("dataset", "ref", "body", "latest_date", "representations", "ref_id", "ref_type") VALUES ('test_dataset_01', 'ref_01', '{}', '2022-07-04'::date, '{}', '', '') RETURNING "api_ref_data"."id"
bibxml-service-test-db-1     | 2022-07-04 02:05:08.284 UTC [82] ERROR:  syntax error, unexpected IDENT_P at end of jsonpath input at character 201
bibxml-service-test-db-1     | 2022-07-04 02:05:08.284 UTC [82] STATEMENT:  SELECT "api_ref_data"."id", "api_ref_data"."dataset", "api_ref_data"."ref", "api_ref_data"."body" FROM "api_ref_data" WHERE "api_ref_data"."id" IN (
bibxml-service-test-db-1     | 	        SELECT id FROM api_ref_data WHERE (body @@ 'test')
bibxml-service-test-db-1     | 	    ) ORDER BY "api_ref_data"."latest_date" DESC LIMIT 400
bibxml-service-test-1 exited with code 1
Aborting on container exit...
[+] Running 3/3
 ⠿ Container bibxml-service-test-1        Stopped                                                                                                                                                                                                                                                                                                                                                                    0.0s
 ⠿ Container bibxml-service-test-redis-1  Stopped                                                                                                                                                                                                                                                                                                                                                                    0.2s
 ⠿ Container bibxml-service-test-db-1     Stopped
```

**Comment by kwkwan** [comment] 2022-07-04 02:40
Hi @stefanomunarini, I ran the test locally and I also got error exit code 1, just like @kesara.  I tried to change the `command` line in `docker-compose.test.yml` to

```
command:
      - /bin/sh
      - -c
      - |
        /wait &&
        python -m coverage run manage.py test
```

I got an error trace like this:

```
bibxml-service-test-1  | ======================================================================
bibxml-service-test-1  | ERROR: xml2rfc_compat.tests.test_fetchers (unittest.loader._FailedTest)
bibxml-service-test-1  | ----------------------------------------------------------------------
bibxml-service-test-1  | ImportError: Failed to import test module: xml2rfc_compat.tests.test_fetchers
bibxml-service-test-1  | Traceback (most recent call last):
bibxml-service-test-1  |   File "/usr/lib/python3.10/unittest/loader.py", line 436, in _find_test_path
bibxml-service-test-1  |     module = self._get_module_from_name(name)
bibxml-service-test-1  |   File "/usr/lib/python3.10/unittest/loader.py", line 377, in _get_module_from_name
bibxml-service-test-1  |     __import__(name)
bibxml-service-test-1  |   File "/code/xml2rfc_compat/tests/test_fetchers.py", line 5, in <module>
bibxml-service-test-1  |     from xml2rfc_compat import fetchers
bibxml-service-test-1  | ImportError: cannot import name 'fetchers' from 'xml2rfc_compat' (/code/xml2rfc_compat/__init__.py)
bibxml-service-test-1  | 
bibxml-service-test-1  | 
bibxml-service-test-1  | ----------------------------------------------------------------------
bibxml-service-test-1  | Ran 34 tests in 3.799s
bibxml-service-test-1  | 
bibxml-service-test-1  | FAILED (errors=1)
bibxml-service-test-1  | Destroying test database for alias 'default'...
bibxml-service-test-1 exited with code 1
```

Is it a hint to solve the error?

**Comment by stefanomunarini** [comment] 2022-07-12 13:00
Merging https://github.com/ietf-ribose/bibxml-service/pull/224 fixed the tests.

Check https://dev.bibxml.org/static/docs/howto/run-tests.html for the docs on how to run the tests locally

**Closed by stefanomunarini** 2022-07-12 13:00 UTC
Labels: documentation, tests
