### ISSUE TITLE
RFC bibxml should not specify document day

### ISSUE THREAD

**Issue by rjsparks** [ietf-ribose/bibxml-service#85] opened 2022-01-18 19:09 UTC
Compare
https://dev.bibxml.org/api/v1/ref/rfcs/RFC8126/?format=bibxml
and
https://xml2rfc.tools.ietf.org/public/rfc/bibxml-rfcs/reference.RFC.8126.xml

Note that the later does not claim `day=1`

RFCs are published with a Year and Month, but not a day*. Please remove day from this rendering for RFCs (day still makes sense for Internet-Drafts).

*April 1st RFCs are published with a day in the header, but to date, the bibxml for them does not contain the day. It is not a requirement for this project to put a day in the bibxml for April 1 RFCs, but we may choose to work on this ourselves as a future enhancement. Note that not all RFCs published on April 1 are April 1st RFCs.

**Comment by ronaldtse** [comment] 2022-01-20 02:25
Confirmed and will fix.

**Comment by strogonoff** [comment] 2022-04-16 13:44
Closing since upstream source issue was closed.

**Closed by strogonoff** 2022-04-16 13:44 UTC
Labels: bug
